version: '3.9'

services:
  webapp:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    pull_policy: always
    restart: always
    expose:
      - ${PORT}
    ports:
      - ${PORT}:80
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80/"]
      interval: 3s
      timeout: 10s
      retries: 10